# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
ko_fi: gpchelkin
buy_me_a_coffee: gpchelkin
custom: ['tinkoff.ru/rm/r_pNKeBoDLLB.jXIdjrpSop/xqHkU97064', 'yoomoney.ru/to/41001421333857', 'github.com/yt-dlp/yt-dlp/blob/master/Maintainers.md']
